---
title: "Data Viz Homework"
author: "Golf Nattapat"
output:
  pdf_document: default
  html_notebook: default
---

## Load package

```{r}
library(tidyverse)
library(patchwork)
library(lubridate)
library(ggplot2)
library(dplyr)
library(ggthemes)
```




## Chart 1 Diamonds quantity of each cut


```{r}
ggplot(diamonds, aes(factor(cut), fill = cut)) +
  geom_bar() +
  labs(title = "Diamonds quantity of each cut",
       x = "Cut",
       y = "Quatity",
       caption = "source : ggplot2 package") +
  theme_minimal()

```


## Chart 2 Price of each diamonds color

```{r}
ggplot(diamonds, aes(factor(color), price, fill =color)) +
  geom_violin() +
  labs(title = "Price of each diamonds color",
       x = "Color",
       y = "Price ($USD)",
       caption = "source : ggplot2 package") +
  theme_minimal() 
  
```

# Chart 3 Quantity of each color and clarity

```{r}
ggplot(diamonds, aes(factor(color), factor(clarity))) +
  geom_count() +
  labs(title = "Quantity of each color and clarity ",
       x = "Color",
       y = "Clarity",
       caption = "source : ggplot2 package") +
  theme_minimal() 
```

## Chart 4 Price of carat (each color and clarity)

```{r}
set.seed(22)
ggplot(sample_n(diamonds, 10000), 
       aes(carat, price)) +
  geom_point(alpha = 0.4) +
  geom_smooth(se=F) +
  theme_minimal() +
  facet_grid(clarity ~ color) +
  labs(title = "Price of carat (each color and clarity) ",
       caption = "source : ggplot2 package") 
```

## Chart 5 Car Weight of each cylinders

```{r}
ggplot(mtcars,aes(factor(cyl),wt)) +
  geom_boxplot() +
  theme_economist() +
  labs(title = "Car Weight of each cylinders ",
       x = "Number of cylinders",
       y = "Weight (1000 lbs)",
       caption = "source : ggplot2 package") 
```


## Chart 6 HP vs. MPG of each Number of carburetors

```{r}
ggplot(mtcars ,aes(hp, mpg)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm", se=F) +
  theme_igray() +
  facet_wrap(~factor(cyl),ncol=1)+
  labs(title = "HP vs. MPG of each Number of carburetors",
       x= "Gross horsepower",
       y="Miles/(US) gallon",
       caption = "source : ggplot2 package") 
```

